### PR TITLE
MDX Implementation, Navbar and styling

### PR DESCRIPTION
**Pull request by AkinariHex**
First change I made is to remove from `next.config.mjs` the obsolete appDir statement.

After I made the implementation of **MDX**, to parse all the markdown the website want to load. We doesn't have an endpoint to get the markdown for the rules so I implemented it with parsing a file from the directory, will edit the parse with the endpoint when ready.

Created a new folder called `components` where I put Navbar component, styled it according to a sample design of an image.

Lastly I edited the metadata of the website and added custom to **Rules** page.

Here's what I achieved with these changes:

https://github.com/5DigitWorldCup/2024Website/assets/28952344/098c8c4a-7836-4423-b10b-05135ddb3ef0

### CODE REVIEW

**Comment by AkinariHex** [comment]
Updated following the new design of the navbar.
To make the table work I changed the file of markdown from .md to .mdx to allow to inject directly html tags and using table/td/td etc.

Also changed default font from Inter to Barlow following the new design.


https://github.com/5DigitWorldCup/2024Website/assets/28952344/791406d4-23ff-4b83-bc36-8d0188bc24df

**Review by L-Mario564 — APPROVED** [review]
Really good work so far. Only thing is that the navbar and the table in the rules page isn't responsive, but I can work on that if you want to, otherwise everything works well on a large screen.

**Comment by AkinariHex** [comment]
About rules page don't remember what have to be fixed in the responsive side, maybe the table (??), for the navbar I didn't the responsive because there is no design about navbar for mobile.

Let me know if you want to address these or I will do it, and if you wish we can address these fixes in a new PR so this can be pushed already.

**Comment by L-Mario564** [comment]
> About rules page don't remember what have to be fixed in the responsive side, maybe the table (??), for the navbar I didn't the responsive because there is no design about navbar for mobile.

Yeah, the table is the only thing that isn't responsive.

> Let me know if you want to address these or I will do it, and if you wish we can address these fixes in a new PR so this can be pushed already.

I'm fine with either, but if you want to work on the landing/home page then go ahead and do that and I'll address these details. And yeah, will get @R0B11 to merge this.

**Pull request merged**
